# Generated by Django 2.1.2 on 2018-10-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_sort',
            field=models.CharField(max_length=20),
        ),
    ]
