# Generated by Django 2.1.2 on 2018-10-29 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20181029_1538'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'default_related_name': 'users'},
        ),
        migrations.AlterField(
            model_name='goods',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='polls.User'),
        ),
    ]
