# Generated by Django 2.1.2 on 2018-10-29 12:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20181029_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_name', models.CharField(max_length=50)),
                ('change_bh', models.CharField(max_length=50)),
                ('modify_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('change_content', models.CharField(max_length=100)),
            ],
        ),
    ]
