# Generated by Django 2.1.2 on 2018-10-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_goodschange'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodschange',
            name='change_sort',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='goodschange',
            name='change_sum',
            field=models.IntegerField(default=0),
        ),
    ]
